version: '3.8'

services:
  backend:
    build:
      context: .              # root of the project
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    working_dir: /app/api
    #volumes:
    #  - .:/app  # optional for live code reloading adn testing

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
